//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chrisandlenka.co.uk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chrisandlenka.co.uk.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be our guest!.
        /// </summary>
        public static string BeOurGuest {
            get {
                return ResourceManager.GetString("BeOurGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEREMONY.
        /// </summary>
        public static string Ceremony {
            get {
                return ResourceManager.GetString("Ceremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Registry.
        /// </summary>
        public static string GiftRegistry {
            get {
                return ResourceManager.GetString("GiftRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We understand many of you have had to travel, take time off work and generally had a few extra expenses. Plus if have seen our tiny patch of land in the UK, then you will know, space is at a primieum.  If you to still get us something, then please consider donating to our honeymoon fund so we have an unforgettable adventure!.
        /// </summary>
        public static string GiftRegistryDesc {
            get {
                return ResourceManager.GetString("GiftRegistryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOTEL.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open The Map.
        /// </summary>
        public static string OpenTheMap {
            get {
                return ResourceManager.GetString("OpenTheMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk.
        /// </summary>
        public static string OtherCulture {
            get {
                return ResourceManager.GetString("OtherCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/flags/slovakia.png.
        /// </summary>
        public static string OtherFlagImageUrl {
            get {
                return ResourceManager.GetString("OtherFlagImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Story.
        /// </summary>
        public static string OurStory {
            get {
                return ResourceManager.GetString("OurStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEPTION.
        /// </summary>
        public static string Reception {
            get {
                return ResourceManager.GetString("Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please RSVP by 1st March 2017.
        /// </summary>
        public static string RsvpDesc {
            get {
                return ResourceManager.GetString("RsvpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail.
        /// </summary>
        public static string RsvpEmail {
            get {
                return ResourceManager.GetString("RsvpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message (optional).
        /// </summary>
        public static string RsvpMessage {
            get {
                return ResourceManager.GetString("RsvpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string RsvpName {
            get {
                return ResourceManager.GetString("RsvpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Guests.
        /// </summary>
        public static string RsvpNumberOfGuests {
            get {
                return ResourceManager.GetString("RsvpNumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string RsvpSend {
            get {
                return ResourceManager.GetString("RsvpSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where &amp; When.
        /// </summary>
        public static string WhereAndWhen {
            get {
                return ResourceManager.GetString("WhereAndWhen", resourceCulture);
            }
        }
    }
}
