//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chrisandlenka2.co.uk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chrisandlenka2.co.uk.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mention our names when making your reservation to recieve the group booking discount..
        /// </summary>
        public static string AccommStErminsDetails {
            get {
                return ResourceManager.GetString("AccommStErminsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to Stay?.
        /// </summary>
        public static string AccommTitle {
            get {
                return ResourceManager.GetString("AccommTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the day on Instagram.
        /// </summary>
        public static string GalleryShareTheDay {
            get {
                return ResourceManager.GetString("GalleryShareTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August 26th, 2017 - London, United Kingdom.
        /// </summary>
        public static string HomeDateAndPlace {
            get {
                return ResourceManager.GetString("HomeDateAndPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accommodation.
        /// </summary>
        public static string MenuAccomm {
            get {
                return ResourceManager.GetString("MenuAccomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our story.
        /// </summary>
        public static string MenuOurStory {
            get {
                return ResourceManager.GetString("MenuOurStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registry.
        /// </summary>
        public static string MenuRegistry {
            get {
                return ResourceManager.GetString("MenuRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rsvp.
        /// </summary>
        public static string MenuRsvp {
            get {
                return ResourceManager.GetString("MenuRsvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wedding.
        /// </summary>
        public static string MenuWedding {
            get {
                return ResourceManager.GetString("MenuWedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk.
        /// </summary>
        public static string OtherCulture {
            get {
                return ResourceManager.GetString("OtherCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/flags/slovakia.png.
        /// </summary>
        public static string OtherFlagImageUrl {
            get {
                return ResourceManager.GetString("OtherFlagImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We understand that many of you have to travel, take time off  and generally have extra expenses in order to celebrate our wedding day with us. However, if you are still considering to get us something as a wedding gift, we would welcome any contributions towards our honeymoon fund to create new memories and unforgettable adventures..
        /// </summary>
        public static string RegistryDetails {
            get {
                return ResourceManager.GetString("RegistryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give the gift of presents.
        /// </summary>
        public static string RegistryTitle {
            get {
                return ResourceManager.GetString("RegistryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Come.
        /// </summary>
        public static string RsvpCantCome {
            get {
                return ResourceManager.GetString("RsvpCantCome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Wait.
        /// </summary>
        public static string RsvpCantWait {
            get {
                return ResourceManager.GetString("RsvpCantWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please let us know if you can make it by.
        /// </summary>
        public static string RsvpDetails1 {
            get {
                return ResourceManager.GetString("RsvpDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st May 2017 at the latest!.
        /// </summary>
        public static string RsvpDetails2 {
            get {
                return ResourceManager.GetString("RsvpDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your E-Mail.
        /// </summary>
        public static string RsvpEmail {
            get {
                return ResourceManager.GetString("RsvpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all fields.
        /// </summary>
        public static string RsvpFormError {
            get {
                return ResourceManager.GetString("RsvpFormError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your RSVP!.
        /// </summary>
        public static string RsvpFormSuccess {
            get {
                return ResourceManager.GetString("RsvpFormSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gf / Df / etc.
        /// </summary>
        public static string RsvpMealDR {
            get {
                return ResourceManager.GetString("RsvpMealDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Preference.
        /// </summary>
        public static string RsvpMealPreference {
            get {
                return ResourceManager.GetString("RsvpMealPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meat.
        /// </summary>
        public static string RsvpMealStandard {
            get {
                return ResourceManager.GetString("RsvpMealStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veg.
        /// </summary>
        public static string RsvpMealVeg {
            get {
                return ResourceManager.GetString("RsvpMealVeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name / Your Guest(s) Names.
        /// </summary>
        public static string RsvpName {
            get {
                return ResourceManager.GetString("RsvpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Requests?.
        /// </summary>
        public static string RsvpSongRequest {
            get {
                return ResourceManager.GetString("RsvpSongRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit RSVP.
        /// </summary>
        public static string RsvpSubmitRsvp {
            get {
                return ResourceManager.GetString("RsvpSubmitRsvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say you&apos;ll be there.
        /// </summary>
        public static string RsvpTitle {
            get {
                return ResourceManager.GetString("RsvpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday August 26th - Bucks &amp; Hens details to follow..
        /// </summary>
        public static string SaveTheDateDetails {
            get {
                return ResourceManager.GetString("SaveTheDateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE THE DATE.
        /// </summary>
        public static string SaveTheDateTitle {
            get {
                return ResourceManager.GetString("SaveTheDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I love you for your beauty, your intelligence, your kindness… and for the way you always know how to make me feel so special. So on top of all the other vows that I will make to you on our wedding day, I also vow to always appreciate how lucky I am..
        /// </summary>
        public static string StoryAboutHer {
            get {
                return ResourceManager.GetString("StoryAboutHer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been my best friend, mentor, playmate, confidant, and my greatest challenge. But most importantly, you are the love of my life and you make me happier than I could ever imagine and more loved than I ever thought possible..
        /// </summary>
        public static string StoryAboutHim {
            get {
                return ResourceManager.GetString("StoryAboutHim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A little about the bride and groom..
        /// </summary>
        public static string StoryDetails {
            get {
                return ResourceManager.GetString("StoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Lenka &amp; Chris on the 26th of August, 2017 to celebrate their union..
        /// </summary>
        public static string StoryTitle {
            get {
                return ResourceManager.GetString("StoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceremony.
        /// </summary>
        public static string WeddingCeremony {
            get {
                return ResourceManager.GetString("WeddingCeremony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Caxton St, Westminster.
        /// </summary>
        public static string WeddingCeremonyAddress1 {
            get {
                return ResourceManager.GetString("WeddingCeremonyAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to London SW1H 0QW.
        /// </summary>
        public static string WeddingCeremonyAddress2 {
            get {
                return ResourceManager.GetString("WeddingCeremonyAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cloisters Suite, St. Ermin&apos;s Hotel.
        /// </summary>
        public static string WeddingCeremonyLocation {
            get {
                return ResourceManager.GetString("WeddingCeremonyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2:45pm - 3:45pm.
        /// </summary>
        public static string WeddingCeremonyTime {
            get {
                return ResourceManager.GetString("WeddingCeremonyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess you could call this a typical &quot;boy meets girl in bar&quot; story but with a twist!  Boy buys girl a drink, girl gives boy phone number. Two months and several thousand kilometers later and said boy and girl are head over heels for each other. Fast forward to today and we&apos;re settling down in our first home ready to tie the knot..
        /// </summary>
        public static string WeddingDetails {
            get {
                return ResourceManager.GetString("WeddingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception.
        /// </summary>
        public static string WeddingReception {
            get {
                return ResourceManager.GetString("WeddingReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Caxton St, Westminster.
        /// </summary>
        public static string WeddingReceptionAddress1 {
            get {
                return ResourceManager.GetString("WeddingReceptionAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to London SW1H 0QW.
        /// </summary>
        public static string WeddingReceptionAddress2 {
            get {
                return ResourceManager.GetString("WeddingReceptionAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal Ballroom, St. Ermin&apos;s Hotel.
        /// </summary>
        public static string WeddingReceptionLocation {
            get {
                return ResourceManager.GetString("WeddingReceptionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4:00pm - Late.
        /// </summary>
        public static string WeddingReceptionTime {
            get {
                return ResourceManager.GetString("WeddingReceptionTime", resourceCulture);
            }
        }
    }
}
